baseURL = "https://eggzuxi.github.io/"
languageCode = "en-us"
theme = "stack"
title = "Quack Quack"
copyright = "Example Person"

DefaultContentLanguage = "en"
hasCJKLanguage = false

[languages.en]
languageName = "English"
title = "Quack Quack"
weight = 1
[languages.en.params.sidebar]
subtitle = ""

[services.disqus]
shortname = "hugo-theme-stack"

[services.googleAnalytics]
id = ""

[pagination]
pagerSize = 3

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = ""

[params.footer]
since = 2020
customText = ""

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
emoji = "🍥"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = true
provider = "disqus"

[params.comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[params.comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[params.comments.beaudar]
repo = ""
issueTerm = "pathname"
label = ""
theme = ""

[params.comments.remark42]
host = ""
site = ""
locale = ""

[params.comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[params.comments.waline]
serverURL = ""
lang = ""
pageview = ""
emoji = ["https://unpkg.com/@waline/emojis@1.0.1/weibo"]
requiredMeta = ["name", "email", "url"]

[params.comments.waline.locale]
admin = "Admin"
placeholder = ""

[params.comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[params.comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[params.comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[params.comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""
proxy = ""

[params.comments.cusdis]
host = ""
id = ""

[params.widgets]
homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
]
page = [
    { type = "toc" },
]

[params.opengraph.twitter]
site = ""
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false
src = ""

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/eggzuxi"
[menu.social.params]
icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false
indices = [
    { name = "tags", weight = 100 },
    { name = "categories", weight = 200 },
]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"], ["<span class=\"math-block\">", "</span>"]]
inline = [["\\(", "\\)"]]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
